package com.controllerface.edeps.enums.costs.commodities;

import com.controllerface.edeps.ProcurementCategory;
import com.controllerface.edeps.ProcurementCost;

import java.util.Arrays;
import java.util.stream.Stream;

/**
 * Created by Stephen on 4/11/2018.
 */
public enum CommodityCategory implements ProcurementCategory
{
    Chemicals(Commodity.EXPLOSIVES,
            Commodity.HYDROGENFUEL,
            Commodity.HYDROGENPEROXIDE,
            Commodity.LIQUIDOXYGEN,
            Commodity.MINERALOIL,
            Commodity.NERVEAGENTS,
            Commodity.PESTICIDES,
            Commodity.SURFACESTABILISERS,
            Commodity.SYNTHETICREAGENTS,
            Commodity.WATER,
            Commodity.DELTAPHOENICISPALMS,
            Commodity.HIPORGANOPHOSPHATES,
            Commodity.KOROKUNGPELLETS,
            Commodity.MEDBSTARLUBE,
            Commodity.TOXANDJIVIROCIDE),

    Consumer_Items(Commodity.CLOTHING,
            Commodity.CONSUMERTECHNOLOGY,
            Commodity.DOMESTICAPPLIANCES,
            Commodity.EVACUATIONSHELTER,
            Commodity.SURVIVALEQUIPMENT,
            Commodity.ALACARAKMOSKINART,
            Commodity.ALTAIRIANSKIN,
            Commodity.ANDULIGAFIREWORKS,
            Commodity.BUCKYBALLBEERMATS,
            Commodity.CRYSTALLINESPHERES,
            Commodity.ELEUTHERMALS,
            Commodity.ESHUUMBRELLAS,
            Commodity.HAVASUPAIDREAMCATCHER,
            Commodity.JAQUESQUINENTIANSTILL,
            Commodity.JARADHARREPUZZLEBOX,
            Commodity.KARETIICOUTURE,
            Commodity.KINAGOVIOLINS,
            Commodity.ALIENEGGS,
            Commodity.MOMUSBOGSPANIEL,
            Commodity.NGUNAMODERNANTIQUES,
            Commodity.NJANGARISADDLES,
            Commodity.OPHIUCHEXINOARTEFACTS,
            Commodity.RAJUKRUMULTISTOVES,
            Commodity.SHANSCHARISORCHID,
            Commodity.SOONTILLRELICS,
            Commodity.TAURICHIMES,
            Commodity.THEHUTTONMUG,
            Commodity.TIOLCEWASTE2PASTEUNITS,
            Commodity.ULTRACOMPACTPROCESSOR,
            Commodity.UZUMOKULOWGWINGS,
            Commodity.VIDAVANTIANLACE,
            Commodity.ZEESSZEANTGRUBGLUE),

    Legal_Drugs(Commodity.BEER,
            Commodity.BOOTLEGLIQUOR,
            Commodity.LIQUOR,
            Commodity.NARCOTICS,
            Commodity.TOBACCO,
            Commodity.WINE,
            Commodity.BASTSNAKEGIN,
            Commodity.BURNHAMBILEDISTILLATE,
            Commodity.CENTAURIMEGAGIN,
            Commodity.CHATEAUDEAEGAEON,
            Commodity.CROMSILVERFESH,
            Commodity.ERANINPEARLWHISKEY,
            Commodity.GEAWENDANCEDUST,
            Commodity.GERASIANGUEUZEBEER,
            Commodity.HARMASILVERSEARUM,
            Commodity.INDIBOURBON,
            Commodity.KAMITRACIGARS,
            Commodity.KONGGAALE,
            Commodity.LAVIANBRANDY,
            Commodity.LEESTIANEVILJUICE,
            Commodity.LUCANONIONHEAD,
            Commodity.LYRAEWEED,
            Commodity.MOTRONAEXPERIENCEJELLY,
            Commodity.ONIONHEAD,
            Commodity.ONIONHEADALPHASTRAIN,
            Commodity.ONIONHEADBETASTRAIN,
            Commodity.PAVONISEARGRUBS,
            Commodity.RUSANIOLDSMOKEY,
            Commodity.SAXONWINE,
            Commodity.TARACHSPICE,
            Commodity.THRUTISCREAM,
            Commodity.WOLFFESH,
            Commodity.WUTHIELOKUFROTH,
            Commodity.YASOKONDILEAF),

    Foods(Commodity.ALGAE,
            Commodity.ANIMALMEAT,
            Commodity.COFFEE,
            Commodity.FISH,
            Commodity.FOODCARTRIDGES,
            Commodity.FRUITANDVEGETABLES,
            Commodity.GRAIN,
            Commodity.SYNTHETICMEAT,
            Commodity.TEA,
            Commodity.AEPYORNISEGG,
            Commodity.ALBINOQUECHUAMAMMOTH,
            Commodity.ANYNACOFFEE,
            Commodity.AROUCACONVENTUALSWEETS,
            Commodity.AZUREMILK,
            Commodity.BALTAHSINEVACUUMKRILL,
            Commodity.CD75KITTENBRANDCOFFEE,
            Commodity.CEREMONIALHEIKETEA,
            Commodity.CETIRABBITS,
            Commodity.CHIERIDANIMARINEPASTE,
            Commodity.COQUIMSPONGIFORMVICTUALS,
            Commodity.DEURINGASTRUFFLES,
            Commodity.DISOMACORN,
            Commodity.EDENAPPLESOFAERIAL,
            Commodity.ESUSEKUCAVIAR,
            Commodity.FUJINTEA,
            Commodity.GIANTIRUKAMASNAILS,
            Commodity.GOMANYAUPONCOFFEE,
            Commodity.HAIDNEBLACKBREW,
            Commodity.HIP10175BUSHMEAT,
            Commodity.HIPPROTOSQUID,
            Commodity.HR7221WHEAT,
            Commodity.JAROUARICE,
            Commodity.KARSUKILOCUSTS,
            Commodity.LIVEHECATESEAWORMS,
            Commodity.LTTHYPERSWEET,
            Commodity.MECHUCOSHIGHTEA,
            Commodity.MOKOJINGBEASTFEAST,
            Commodity.MUKUSUBIICHITINOS,
            Commodity.MULACHIGIANTFUNGUS,
            Commodity.NERITUSBERRIES,
            Commodity.OCHOENGCHILLIES,
            Commodity.ORRERIANVICIOUSBREW,
            Commodity.SANUMADECORATIVEMEAT,
            Commodity.TANMARKTRANQUILTEA,
            Commodity.USZAIANTREEGRUB,
            Commodity.UTGAROARMILLENNIALEGGS,
            Commodity.VOIDEXTRACTCOFFEE,
            Commodity.WHEEMETEWHEATCAKES,
            Commodity.WITCHHAULKOBEBEEF,
            Commodity.ETHGREZETEABUDS),

    Industrial_Materials(Commodity.CERAMICCOMPOSITES,
            Commodity.CMMCOMPOSITE,
            Commodity.INSULATINGMEMBRANE,
            Commodity.METAALLOYS,
            Commodity.MICROWEAVECOOLINGHOSES,
            Commodity.NEOFABRICINSULATION,
            Commodity.POLYMERS,
            Commodity.SEMICONDUCTORS,
            Commodity.SUPERCONDUCTORS),

    Machinery(Commodity.ARTICULATIONMOTORS,
            Commodity.ATMOSPHERICPROCESSORS,
            Commodity.BUILDINGFABRICATORS,
            Commodity.CROPHARVESTERS,
            Commodity.EMERGENCYPOWERCELLS,
            Commodity.ENERGYGRIDASSEMBLY,
            Commodity.EXHAUSTMANIFOLD,
            Commodity.GEOLOGICALEQUIPMENT,
            Commodity.HEATSINKINTERLINK,
            Commodity.HNSHOCKMOUNT,
            Commodity.MAGNETICEMITTERCOIL,
            Commodity.MARINEEQUIPMENT,
            Commodity.MICROBIALFURNACES,
            Commodity.MINERALEXTRACTORS,
            Commodity.MODULARTERMINALS,
            Commodity.POWERCONVERTER,
            Commodity.POWERGENERATORS,
            Commodity.POWERTRANSFERBUS,
            Commodity.RADIATIONBAFFLE,
            Commodity.REINFORCEDMOUNTINGPLATE,
            Commodity.SKIMMERCOMPONENTS,
            Commodity.THERMALCOOLINGUNITS,
            Commodity.WATERPURIFIERS,
            Commodity.GIANTVERRIX,
            Commodity.NONEUCLIDIANEXOTANKS,
            Commodity.VOLKHABBEEDRONES,
            Commodity.WULPAHYPERBORESYSTEMS),

    Medicines(Commodity.ADVANCEDMEDICINES,
            Commodity.AGRIMEDICINES,
            Commodity.BASICMEDICINES,
            Commodity.COMBATSTABILISERS,
            Commodity.PERFORMANCEENHANCERS,
            Commodity.PROGENITORCELLS,
            Commodity.AGANIPPERUSH,
            Commodity.ALYABODYSOAP,
            Commodity.HONESTYPILLS,
            Commodity.KACHIRIGINFILTERLEECHES,
            Commodity.PANTAAPRAYERSTICKS,
            Commodity.TERRAMATERBLOODBORES,
            Commodity.VHERCULISBODYRUB,
            Commodity.VEGASLIMWEED,
            Commodity.WATERSOFSHINTARA),

    Metals(Commodity.ALUMINIUM,
            Commodity.BERYLLIUM,
            Commodity.BISMUTH,
            Commodity.COBALT,
            Commodity.COPPER,
            Commodity.GALLIUM,
            Commodity.GOLD,
            Commodity.HAFNIUM178,
            Commodity.INDIUM,
            Commodity.LANTHANUM,
            Commodity.LITHIUM,
            Commodity.OSMIUM,
            Commodity.PALLADIUM,
            Commodity.PLATINUM,
            Commodity.PLATINUMALLOY,
            Commodity.PRASEODYMIUM,
            Commodity.SAMARIUM,
            Commodity.SILVER,
            Commodity.TANTALUM,
            Commodity.THALLIUM,
            Commodity.THORIUM,
            Commodity.TITANIUM,
            Commodity.URANIUM,
            Commodity.CHERBONESBLOODCRYSTALS,
            Commodity.HELVETITJPEARLS,
            Commodity.NGADANDARIFIREOPALS,
            Commodity.SOTHISCRYSTALLINEGOLD),

    Minerals(Commodity.BAUXITE,
            Commodity.BERTRANDITE,
            Commodity.BROMELLITE,
            Commodity.COLTAN,
            Commodity.CRYOLITE,
            Commodity.GALLITE,
            Commodity.GOSLARITE,
            Commodity.INDITE,
            Commodity.JADEITE,
            Commodity.LEPIDOLITE,
            Commodity.LITHIUMHYDROXIDE,
            Commodity.LOWTEMPERATUREDIAMONDS,
            Commodity.METHANECLATHRATE,
            Commodity.METHANOLMONOHYDRATECRYSTALS,
            Commodity.MOISSANITE,
            Commodity.PAINITE,
            Commodity.PYROPHYLLITE,
            Commodity.RUTILE,
            Commodity.TAAFFEITE,
            Commodity.URANINITE),

    Salvage(Commodity.AIRELICS,
            Commodity.USSCARGOANCIENTARTEFACT,
            Commodity.ANCIENTCASKET,
            Commodity.ANCIENTORB,
            Commodity.ANCIENTRELIC,
            Commodity.ANCIENTTABLET,
            Commodity.ANCIENTTOTEM,
            Commodity.ANCIENTURN,
            Commodity.ANTIMATTERCONTAINMENTUNIT,
            Commodity.ANTIQUEJEWELLERY,
            Commodity.ANTIQUITIES,
            Commodity.ASSAULTPLANS,
            Commodity.USSCARGOBLACKBOX,
            Commodity.COMMERCIALSAMPLES,
            Commodity.DAMAGEDESCAPEPOD,
            Commodity.DATACORE,
            Commodity.DIPLOMATICBAG,
            Commodity.EARTHRELICS,
            Commodity.ENCRYPTEDCORRESPONDENCE,
            Commodity.ENCRYPTEDDATASTORAGE,
            Commodity.USSCARGOEXPERIMENTALCHEMICALS,
            Commodity.FOSSILREMNANTS,
            Commodity.GENEBANK,
            Commodity.GEOLOGICALSAMPLES,
            Commodity.HOSTAGE,
            Commodity.LARGESURVEYDATACACHE,
            Commodity.MILITARYINTELLIGENCE,
            Commodity.USSCARGOMILITARYPLANS,
            Commodity.MYSTERIOUSIDOL,
            Commodity.OCCUPIEDESCAPEPOD,
            Commodity.PERSONALEFFECTS,
            Commodity.POLITICALPRISONER,
            Commodity.PRECIOUSGEMS,
            Commodity.PROHIBITEDRESEARCHMATERIALS,
            Commodity.USSCARGOPROTOTYPETECH,
            Commodity.USSCARGORAREARTWORK,
            Commodity.USSCARGOREBELTRANSMISSIONS,
            Commodity.SAP8CORECONTAINER,
            Commodity.SCIENTIFICRESEARCH,
            Commodity.SCIENTIFICSAMPLES,
            Commodity.SMALLSURVEYDATACACHE,
            Commodity.SPACEPIONEERRELICS,
            Commodity.TACTICALDATA,
            Commodity.USSCARGOTECHNICALBLUEPRINTS,
            Commodity.THARGOIDBASILISKTISSUESAMPLE,
            Commodity.THARGOIDBIOLOGICALMATTER,
            Commodity.THARGOIDCYCLOPSTISSUESAMPLE,
            Commodity.THARGOIDHEART,
            Commodity.THARGOIDLINK,
            Commodity.THARGOIDMEDUSATISSUESAMPLE,
            Commodity.THARGOIDPROBE,
            Commodity.THARGOIDRESIN,
            Commodity.THARGOIDSCOUTTISSUESAMPLE,
            Commodity.THARGOIDSENSOR,
            Commodity.THARGOIDTECHNOLOGYSAMPLES,
            Commodity.TIMECAPSULE,
            Commodity.USSCARGOTRADEDATA,
            Commodity.TRINKETSOFHIDDENFORTUNE,
            Commodity.UNSTABLEDATACORE,
            Commodity.WRECKAGECOMPONENTS,
            Commodity.GALACTICTRAVELGUIDES,
            Commodity.PERSONALGIFTS),

    Slaves(Commodity.IMPERIALSLAVES,
            Commodity.SLAVES,
            Commodity.MASTERCHEFS),

    Technology(Commodity.ADVANCEDCATALYSERS,
            Commodity.ANIMALMONITORS,
            Commodity.AQUAPONICSYSTEMS,
            Commodity.AUTOFABRICATORS,
            Commodity.BIOREDUCINGLICHEN,
            Commodity.COMPUTERCOMPONENTS,
            Commodity.HAZARDOUSENVIRONMENTSUITS,
            Commodity.HARDWAREDIAGNOSTICSENSOR,
            Commodity.IONDISTRIBUTOR,
            Commodity.TERRAINENRICHMENTSYSTEMS,
            Commodity.MEDICALDIAGNOSTICEQUIPMENT,
            Commodity.MICROCONTROLLERS,
            Commodity.MUONIMAGER,
            Commodity.NANOBREAKERS,
            Commodity.RESONATINGSEPARATORS,
            Commodity.ROBOTICS,
            Commodity.STRUCTURALREGULATORS,
            Commodity.TELEMETRYSUITE,
            Commodity.AZCANCRIFORMULA42,
            Commodity.XIHEBIOMORPHICCOMPANIONS),

    Textiles(Commodity.CONDUCTIVEFABRICS,
            Commodity.LEATHER,
            Commodity.MILITARYGRADEFABRICS,
            Commodity.NATURALFABRICS,
            Commodity.SYNTHETICFABRICS,
            Commodity.BANKIAMPHIBIOUSLEATHER,
            Commodity.BELALANSRAYLEATHER,
            Commodity.CHAMELEONCLOTH,
            Commodity.DAMNACARAPACES,
            Commodity.JOTUNMOOKAH,
            Commodity.RAPABAOSNAKESKINS,
            Commodity.VANAYEQUICERATOMORPHAFUR),

    Waste(Commodity.BIOWASTE,
            Commodity.CHEMICALWASTE,
            Commodity.SCRAP,
            Commodity.TOXICWASTE),

    Weapons(Commodity.BATTLEWEAPONS,
            Commodity.LANDMINES,
            Commodity.NONLETHALWEAPONS,
            Commodity.PERSONALWEAPONS,
            Commodity.REACTIVEARMOUR,
            Commodity.BORASETANIPATHOGENETICS,
            Commodity.GILYASIGNATUREWEAPONS,
            Commodity.HIP118311SWARM,
            Commodity.HOLVADUELLINGBLADES,
            Commodity.KAMORINHISTORICWEAPONS),

    Drones(Commodity.DRONES),

    Power_Play(Commodity.AISLINGMEDIAMATERIALS,
            Commodity.AISLINGMEDIARESOURCES,
            Commodity.AISLINGPROMOTIONALMATERIALS,
            Commodity.ALLIANCETRADEAGREEMENTS,
            Commodity.ALLIANCELEGASLATIVECONTRACTS,
            Commodity.ALLIANCELEGASLATIVERECORDS,
            Commodity.LAVIGNYCORRUPTIONDOSSIERS,
            Commodity.LAVIGNYFIELDSUPPLIES,
            Commodity.LAVIGNYGARISONSUPPLIES,
            Commodity.RESTRICTEDPACKAGE,
            Commodity.LIBERALCAMPAIGNMATERIALS,
            Commodity.FEDERALAID,
            Commodity.FEDERALTRADECONTRACTS,
            Commodity.LOANEDARMS,
            Commodity.PATREUSFIELDSUPPLIES,
            Commodity.PATREUSGARISONSUPPLIES,
            Commodity.RESTRICTEDINTEL,
            Commodity.REPUBLICANFIELDSUPPLIES,
            Commodity.REPUBLICANGARISONSUPPLIES,
            Commodity.SIRIUSFRANCHISEPACKAGE,
            Commodity.SIRIUSCOMMERCIALCONTRACTS,
            Commodity.SIRIUSINDUSTRIALEQUIPMENT,
            Commodity.TORVALCOMMERCIALCONTRACTS,
            Commodity.IMPERIALPRISONER,
            Commodity.UTOPIANPUBLICITY,
            Commodity.UTOPIANFIELDSUPPLIES,
            Commodity.UTOPIANDISSIDENT,
            Commodity.ILLICITCONSIGNMENT,
            Commodity.UNMARKEDWEAPONS,
            Commodity.ONIONHEADSAMPLES,
            Commodity.COUNTERCULTURESUPPORT,
            Commodity.MARKEDSLAVES,
            Commodity.TORVALDEEDS,
            Commodity.ONIONHEADDERIVATIVES,
            Commodity.OUTOFDATEGOODS,
            Commodity.UNDERGROUNDSUPPORT,
            Commodity.GROMCOUNTERINTELLIGENCE,
            Commodity.GROMWARTROPHIES),

    UNKNOWN();

    private final Commodity[] commodities;

    CommodityCategory(Commodity ... commodities)
    {
        this.commodities = commodities;
    }

    public boolean hasCommodity(Commodity commodity)
    {
        return commodities()
                .anyMatch(m -> m == commodity);
    }

    public static ProcurementCategory findMatchingCategory(ProcurementCost cost)
    {
        if (!(cost instanceof Commodity)) return UNKNOWN;
        Commodity commodity = ((Commodity) cost);
        return Arrays.stream(values())
                .filter(category->category.hasCommodity(commodity))
                .findFirst().orElse(UNKNOWN);
    }
    public Stream<Commodity> commodities()
    {
        return Arrays.stream(commodities);
    }

    @Override
    public String toString()
    {
        return super.toString().replace("_", " ");
    }
}
