package com.controllerface.edeps.structures.equipment.modules;

import com.controllerface.edeps.ProcurementType;
import com.controllerface.edeps.ShipModule;
import com.controllerface.edeps.structures.craftable.experimentals.ExperimentalType;
import com.controllerface.edeps.structures.craftable.modifications.ModificationType;

import java.util.Arrays;

/**
 * Created by Stephen on 4/25/2018.
 */
public enum CoreInternalModule implements ShipModule
{
    /**
     * Cargo Bay Door
     */
    //ModularCargoBayDoor(text),

    /**
     * Cockpits
     */

//    Vulture_Cockpit(text),
//    Python_Cockpit(text),
//    TypeX_Cockpit(text),


    /**
     * Ship Armor
     */

    dolphin_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    dolphin_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    dolphin_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    dolphin_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    dolphin_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    ferdelance_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    ferdelance_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    ferdelance_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    ferdelance_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),
    ferdelance_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),

    python_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    python_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    python_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    python_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    python_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    belugaliner_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    belugaliner_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    belugaliner_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    belugaliner_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    belugaliner_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    orca_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    orca_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    orca_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    orca_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    orca_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    asp_scout_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    asp_scout_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    asp_scout_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    asp_scout_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    asp_scout_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    asp_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    asp_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    asp_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    asp_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    asp_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    independant_trader_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    independant_trader_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    independant_trader_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    independant_trader_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    independant_trader_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    vulture_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    vulture_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    vulture_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    vulture_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    vulture_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    viper_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    viper_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    viper_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    viper_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    viper_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    diamondbackxl_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    diamondbackxl_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    diamondbackxl_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    diamondbackxl_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),
    diamondbackxl_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),

    adder_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    adder_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    adder_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    adder_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    adder_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    diamondback_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    diamondback_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    diamondback_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    diamondback_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    diamondback_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    viper_mkiv_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    viper_mkiv_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    viper_mkiv_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    viper_mkiv_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    viper_mkiv_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    anaconda_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    anaconda_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    anaconda_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    anaconda_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),
    anaconda_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),

    cobramkiii_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    cobramkiii_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    cobramkiii_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    cobramkiii_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    cobramkiii_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    type9_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    type9_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    type9_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    type9_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    type9_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    type7_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    type7_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    type7_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    type7_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    type7_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    cobramkiv_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    cobramkiv_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    cobramkiv_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    cobramkiv_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    cobramkiv_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    eagle_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    eagle_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    eagle_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    eagle_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    eagle_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    hauler_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    hauler_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    hauler_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    hauler_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    hauler_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    sidewinder_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    sidewinder_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    sidewinder_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    sidewinder_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    sidewinder_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    type6_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    type6_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    type6_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    type6_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    type6_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    empire_trader_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    empire_trader_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    empire_trader_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    empire_trader_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    empire_trader_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    federation_dropship_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    federation_dropship_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    federation_dropship_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    federation_dropship_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    federation_dropship_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    cutter_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    cutter_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    cutter_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    cutter_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),
    cutter_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),

    empire_eagle_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    empire_eagle_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    empire_eagle_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    empire_eagle_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    empire_eagle_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    typex_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    typex_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    typex_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    typex_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    typex_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    federation_corvette_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    federation_corvette_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    federation_corvette_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    federation_corvette_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),
    federation_corvette_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),

    empire_courier_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    empire_courier_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    empire_courier_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    empire_courier_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    empire_courier_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    federation_gunship_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    federation_gunship_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    federation_gunship_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    federation_gunship_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    federation_gunship_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    type9_military_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    type9_military_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    type9_military_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    type9_military_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    type9_military_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),

    federation_dropship_mkii_armour_grade1(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Lightweight"),
    federation_dropship_mkii_armour_grade2(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reinforced"),
    federation_dropship_mkii_armour_grade3(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Military Grade"),
    federation_dropship_mkii_armour_reactive(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Reactive"),
    federation_dropship_mkii_armour_mirrored(ModificationType.Bulkheads, ExperimentalType.Bulkheads,
            "Mirrored"),


    /**
     * Power Plants
     */

    int_powerplant_size2_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "2E Standard"),
    int_powerplant_size2_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "2D Standard"),
    int_powerplant_size2_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "2C Standard"),
    int_powerplant_size2_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "2B Standard"),
    int_powerplant_size2_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "2A Standard"),

    int_powerplant_size3_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "3E Standard"),
    int_powerplant_size3_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "3D Standard"),
    int_powerplant_size3_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "3C Standard"),
    int_powerplant_size3_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "3B Standard"),
    int_powerplant_size3_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "3A Standard"),

    int_powerplant_size4_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "4E Standard"),
    int_powerplant_size4_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "4D Standard"),
    int_powerplant_size4_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "4C Standard"),
    int_powerplant_size4_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "4B Standard"),
    int_powerplant_size4_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "4A Standard"),

    int_powerplant_size5_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "5E Standard"),
    int_powerplant_size5_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "5D Standard"),
    int_powerplant_size5_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "5C Standard"),
    int_powerplant_size5_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "5B Standard"),
    int_powerplant_size5_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "5A Standard"),

    int_powerplant_size6_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "6E Standard"),
    int_powerplant_size6_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "6D Standard"),
    int_powerplant_size6_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "6C Standard"),
    int_powerplant_size6_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "6B Standard"),
    int_powerplant_size6_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "6A Standard"),

    int_powerplant_size7_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "7E Standard"),
    int_powerplant_size7_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "7D Standard"),
    int_powerplant_size7_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "7C Standard"),
    int_powerplant_size7_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "7B Standard"),
    int_powerplant_size7_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "7A Standard"),

    int_powerplant_size8_class1(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "8E Standard"),
    int_powerplant_size8_class2(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "8D Standard"),
    int_powerplant_size8_class3(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "8C Standard"),
    int_powerplant_size8_class4(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "8B Standard"),
    int_powerplant_size8_class5(ModificationType.Power_Plant, ExperimentalType.Power_Plant,
            "8A Standard"),


    /**
     * Thrusters
     */

    int_engine_size2_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "2E Standard"),
    int_engine_size2_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "2D Standard"),
    int_engine_size2_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "2C Standard"),
    int_engine_size2_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "2B Standard"),
    int_engine_size2_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "2A Standard"),

    int_engine_size3_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "3E Standard"),
    int_engine_size3_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "3D Standard"),
    int_engine_size3_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "3C Standard"),
    int_engine_size3_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "3B Standard"),
    int_engine_size3_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "3A Standard"),

    int_engine_size4_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "4E Standard"),
    int_engine_size4_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "4D Standard"),
    int_engine_size4_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "4C Standard"),
    int_engine_size4_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "4B Standard"),
    int_engine_size4_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "4A Standard"),

    int_engine_size5_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "5E Standard"),
    int_engine_size5_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "5D Standard"),
    int_engine_size5_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "5C Standard"),
    int_engine_size5_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "5B Standard"),
    int_engine_size5_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "5A Standard"),

    int_engine_size6_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "6E Standard"),
    int_engine_size6_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "6D Standard"),
    int_engine_size6_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "6C Standard"),
    int_engine_size6_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "6B Standard"),
    int_engine_size6_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "6A Standard"),

    int_engine_size7_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "7E Standard"),
    int_engine_size7_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "7D Standard"),
    int_engine_size7_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "7C Standard"),
    int_engine_size7_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "7B Standard"),
    int_engine_size7_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "7A Standard"),

    int_engine_size8_class1(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "8E Standard"),
    int_engine_size8_class2(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "8D Standard"),
    int_engine_size8_class3(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "8C Standard"),
    int_engine_size8_class4(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "8B Standard"),
    int_engine_size8_class5(ModificationType.Thrusters, ExperimentalType.Thrusters,
            "8A Standard"),


    /**
     * Frame Shift Drives
     */

    int_hyperdrive_size2_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "2E Standard"),
    int_hyperdrive_size2_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "2D Standard"),
    int_hyperdrive_size2_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "2C Standard"),
    int_hyperdrive_size2_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "2B Standard"),
    int_hyperdrive_size2_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "2A Standard"),

    int_hyperdrive_size3_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "3E Standard"),
    int_hyperdrive_size3_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "3D Standard"),
    int_hyperdrive_size3_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "3C Standard"),
    int_hyperdrive_size3_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "3B Standard"),
    int_hyperdrive_size3_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "3A Standard"),

    int_hyperdrive_size4_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "4E Standard"),
    int_hyperdrive_size4_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "4D Standard"),
    int_hyperdrive_size4_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "4C Standard"),
    int_hyperdrive_size4_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "4B Standard"),
    int_hyperdrive_size4_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "4A Standard"),

    int_hyperdrive_size5_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "5E Standard"),
    int_hyperdrive_size5_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "5D Standard"),
    int_hyperdrive_size5_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "5C Standard"),
    int_hyperdrive_size5_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "5B Standard"),
    int_hyperdrive_size5_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "5A Standard"),

    int_hyperdrive_size6_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "6E Standard"),
    int_hyperdrive_size6_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "6D Standard"),
    int_hyperdrive_size6_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "6C Standard"),
    int_hyperdrive_size6_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "6B Standard"),
    int_hyperdrive_size6_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "6A Standard"),

    int_hyperdrive_size7_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "7E Standard"),
    int_hyperdrive_size7_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "7D Standard"),
    int_hyperdrive_size7_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "7C Standard"),
    int_hyperdrive_size7_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "7B Standard"),
    int_hyperdrive_size7_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "7A Standard"),

    int_hyperdrive_size8_class1(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "8E Standard"),
    int_hyperdrive_size8_class2(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "8D Standard"),
    int_hyperdrive_size8_class3(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "8C Standard"),
    int_hyperdrive_size8_class4(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "8B Standard"),
    int_hyperdrive_size8_class5(ModificationType.Frame_Shift_Drive, ExperimentalType.Frame_Shift_Drive,
            "8A Standard"),


    /**
     * Life-Support Systems
     */

    int_lifesupport_size1_class1(ModificationType.Life_Support, null,
            "1E Standard"),
    int_lifesupport_size1_class2(ModificationType.Life_Support, null,
            "1D Standard"),
    int_lifesupport_size1_class3(ModificationType.Life_Support, null,
            "1C Standard"),
    int_lifesupport_size1_class4(ModificationType.Life_Support, null,
            "1B Standard"),
    int_lifesupport_size1_class5(ModificationType.Life_Support, null,
            "1A Standard"),

    int_lifesupport_size2_class1(ModificationType.Life_Support, null,
            "2E Standard"),
    int_lifesupport_size2_class2(ModificationType.Life_Support, null,
            "2D Standard"),
    int_lifesupport_size2_class3(ModificationType.Life_Support, null,
            "2C Standard"),
    int_lifesupport_size2_class4(ModificationType.Life_Support, null,
            "2B Standard"),
    int_lifesupport_size2_class5(ModificationType.Life_Support, null,
            "2A Standard"),

    int_lifesupport_size3_class1(ModificationType.Life_Support, null,
            "3E Standard"),
    int_lifesupport_size3_class2(ModificationType.Life_Support, null,
            "3D Standard"),
    int_lifesupport_size3_class3(ModificationType.Life_Support, null,
            "3C Standard"),
    int_lifesupport_size3_class4(ModificationType.Life_Support, null,
            "3B Standard"),
    int_lifesupport_size3_class5(ModificationType.Life_Support, null,
            "3A Standard"),

    int_lifesupport_size4_class1(ModificationType.Life_Support, null,
            "4E Standard"),
    int_lifesupport_size4_class2(ModificationType.Life_Support, null,
            "4D Standard"),
    int_lifesupport_size4_class3(ModificationType.Life_Support, null,
            "4C Standard"),
    int_lifesupport_size4_class4(ModificationType.Life_Support, null,
            "4B Standard"),
    int_lifesupport_size4_class5(ModificationType.Life_Support, null,
            "4A Standard"),

    int_lifesupport_size5_class1(ModificationType.Life_Support, null,
            "5E Standard"),
    int_lifesupport_size5_class2(ModificationType.Life_Support, null,
            "5D Standard"),
    int_lifesupport_size5_class3(ModificationType.Life_Support, null,
            "5C Standard"),
    int_lifesupport_size5_class4(ModificationType.Life_Support, null,
            "5B Standard"),
    int_lifesupport_size5_class5(ModificationType.Life_Support, null,
            "5A Standard"),

    int_lifesupport_size6_class1(ModificationType.Life_Support, null,
            "6E Standard"),
    int_lifesupport_size6_class2(ModificationType.Life_Support, null,
            "6D Standard"),
    int_lifesupport_size6_class3(ModificationType.Life_Support, null,
            "6C Standard"),
    int_lifesupport_size6_class4(ModificationType.Life_Support, null,
            "6B Standard"),
    int_lifesupport_size6_class5(ModificationType.Life_Support, null,
            "6A Standard"),

    int_lifesupport_size7_class1(ModificationType.Life_Support, null,
            "7E Standard"),
    int_lifesupport_size7_class2(ModificationType.Life_Support, null,
            "7D Standard"),
    int_lifesupport_size7_class3(ModificationType.Life_Support, null,
            "7C Standard"),
    int_lifesupport_size7_class4(ModificationType.Life_Support, null,
            "7B Standard"),
    int_lifesupport_size7_class5(ModificationType.Life_Support, null,
            "7A Standard"),

    int_lifesupport_size8_class1(ModificationType.Life_Support, null,
            "8E Standard"),
    int_lifesupport_size8_class2(ModificationType.Life_Support, null,
            "8D Standard"),
    int_lifesupport_size8_class3(ModificationType.Life_Support, null,
            "8C Standard"),
    int_lifesupport_size8_class4(ModificationType.Life_Support, null,
            "8B Standard"),
    int_lifesupport_size8_class5(ModificationType.Life_Support, null,
            "8A Standard"),


    /**
     * Power Distributors
     */

    int_powerdistributor_size1_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "1E Standard"),
    int_powerdistributor_size1_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "1D Standard"),
    int_powerdistributor_size1_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "1C Standard"),
    int_powerdistributor_size1_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "1B Standard"),
    int_powerdistributor_size1_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "1A Standard"),

    int_powerdistributor_size2_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "2E Standard"),
    int_powerdistributor_size2_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "2D Standard"),
    int_powerdistributor_size2_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "2C Standard"),
    int_powerdistributor_size2_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "2B Standard"),
    int_powerdistributor_size2_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "2A Standard"),

    int_powerdistributor_size3_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "3E Standard"),
    int_powerdistributor_size3_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "3D Standard"),
    int_powerdistributor_size3_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "3C Standard"),
    int_powerdistributor_size3_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "3B Standard"),
    int_powerdistributor_size3_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "3A Standard"),

    int_powerdistributor_size4_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "4E Standard"),
    int_powerdistributor_size4_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "4D Standard"),
    int_powerdistributor_size4_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "4C Standard"),
    int_powerdistributor_size4_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "4B Standard"),
    int_powerdistributor_size4_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "4A Standard"),

    int_powerdistributor_size5_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "5E Standard"),
    int_powerdistributor_size5_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "5D Standard"),
    int_powerdistributor_size5_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "5C Standard"),
    int_powerdistributor_size5_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "5B Standard"),
    int_powerdistributor_size5_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "5A Standard"),

    int_powerdistributor_size6_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "6E Standard"),
    int_powerdistributor_size6_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "6D Standard"),
    int_powerdistributor_size6_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "6C Standard"),
    int_powerdistributor_size6_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "6B Standard"),
    int_powerdistributor_size6_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "6A Standard"),

    int_powerdistributor_size7_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "7E Standard"),
    int_powerdistributor_size7_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "7D Standard"),
    int_powerdistributor_size7_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "7C Standard"),
    int_powerdistributor_size7_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "7B Standard"),
    int_powerdistributor_size7_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "7A Standard"),

    int_powerdistributor_size8_class1(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "8E Standard"),
    int_powerdistributor_size8_class2(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "8D Standard"),
    int_powerdistributor_size8_class3(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "8C Standard"),
    int_powerdistributor_size8_class4(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "8B Standard"),
    int_powerdistributor_size8_class5(ModificationType.Power_Distributor, ExperimentalType.Power_Distributor,
            "8A Standard"),


    /**
     * Sensors
     */

    int_sensors_size1_class1(ModificationType.Sensors, null,
            "1E Standard"),
    int_sensors_size1_class2(ModificationType.Sensors, null,
            "1D Standard"),
    int_sensors_size1_class3(ModificationType.Sensors, null,
            "1C Standard"),
    int_sensors_size1_class4(ModificationType.Sensors, null,
            "1B Standard"),
    int_sensors_size1_class5(ModificationType.Sensors, null,
            "1A Standard"),

    int_sensors_size2_class1(ModificationType.Sensors, null,
            "2E Standard"),
    int_sensors_size2_class2(ModificationType.Sensors, null,
            "2D Standard"),
    int_sensors_size2_class3(ModificationType.Sensors, null,
            "2C Standard"),
    int_sensors_size2_class4(ModificationType.Sensors, null,
            "2B Standard"),
    int_sensors_size2_class5(ModificationType.Sensors, null,
            "2A Standard"),

    int_sensors_size3_class1(ModificationType.Sensors, null,
            "3E Standard"),
    int_sensors_size3_class2(ModificationType.Sensors, null,
            "3D Standard"),
    int_sensors_size3_class3(ModificationType.Sensors, null,
            "3C Standard"),
    int_sensors_size3_class4(ModificationType.Sensors, null,
            "3B Standard"),
    int_sensors_size3_class5(ModificationType.Sensors, null,
            "3A Standard"),

    int_sensors_size4_class1(ModificationType.Sensors, null,
            "4E Standard"),
    int_sensors_size4_class2(ModificationType.Sensors, null,
            "4D Standard"),
    int_sensors_size4_class3(ModificationType.Sensors, null,
            "4C Standard"),
    int_sensors_size4_class4(ModificationType.Sensors, null,
            "4B Standard"),
    int_sensors_size4_class5(ModificationType.Sensors, null,
            "4A Standard"),

    int_sensors_size5_class1(ModificationType.Sensors, null,
            "5E Standard"),
    int_sensors_size5_class2(ModificationType.Sensors, null,
            "5D Standard"),
    int_sensors_size5_class3(ModificationType.Sensors, null,
            "5C Standard"),
    int_sensors_size5_class4(ModificationType.Sensors, null,
            "5B Standard"),
    int_sensors_size5_class5(ModificationType.Sensors, null,
            "5A Standard"),

    int_sensors_size6_class1(ModificationType.Sensors, null,
            "6E Standard"),
    int_sensors_size6_class2(ModificationType.Sensors, null,
            "6D Standard"),
    int_sensors_size6_class3(ModificationType.Sensors, null,
            "6C Standard"),
    int_sensors_size6_class4(ModificationType.Sensors, null,
            "6B Standard"),
    int_sensors_size6_class5(ModificationType.Sensors, null,
            "6A Standard"),

    int_sensors_size7_class1(ModificationType.Sensors, null,
            "7E Standard"),
    int_sensors_size7_class2(ModificationType.Sensors, null,
            "7D Standard"),
    int_sensors_size7_class3(ModificationType.Sensors, null,
            "7C Standard"),
    int_sensors_size7_class4(ModificationType.Sensors, null,
            "7B Standard"),
    int_sensors_size7_class5(ModificationType.Sensors, null,
            "7A Standard"),

    int_sensors_size8_class1(ModificationType.Sensors, null,
            "8E Standard"),
    int_sensors_size8_class2(ModificationType.Sensors, null,
            "8D Standard"),
    int_sensors_size8_class3(ModificationType.Sensors, null,
            "8C Standard"),
    int_sensors_size8_class4(ModificationType.Sensors, null,
            "8B Standard"),
    int_sensors_size8_class5(ModificationType.Sensors, null,
            "8A Standard"),


    /**
     * Fuel Tanks
     */

    int_fueltank_size1_class3(null, null,
            "1C Standard"),
    int_fueltank_size2_class3(null, null,
            "2C Standard"),
    int_fueltank_size3_class3(null, null,
            "3C Standard"),
    int_fueltank_size4_class3(null, null,
            "4C Standard"),
    int_fueltank_size5_class3(null, null,
            "5C Standard"),
    int_fueltank_size6_class3(null, null,
            "6C Standard"),
    int_fueltank_size7_class3(null, null,
            "7C Standard"),
    int_fueltank_size8_class3(null, null,
            "8C Standard"),


    /**
     * Guardian Equipment
     */

    // todo: fine ENUM values for these
    // Guardian Hybrid Power Distributor

    int_guardianpowerplant_size2(null, null,
            "2A Hybrid"),
    int_guardianpowerplant_size3(null, null,
            "3A Hybrid"),
    int_guardianpowerplant_size4(null, null,
            "4A Hybrid"),
    int_guardianpowerplant_size5(null, null,
            "5A Hybrid"),
    int_guardianpowerplant_size6(null, null,
            "6A Hybrid"),
    int_guardianpowerplant_size7(null, null,
            "7A Hybrid"),
    int_guardianpowerplant_size8(null, null,
            "8A Hybrid"),

    ;

    private final String text;
    private final ProcurementType modificationType;
    private final ProcurementType experimentalType;

    CoreInternalModule(ProcurementType modificationType, ProcurementType experimentalType, String text)
    {
        this.modificationType = modificationType;
        this.experimentalType = experimentalType;
        this.text = text;
    }

    public ProcurementType modificationType()
    {
        return modificationType;
    }

    public ProcurementType experimentalType()
    {
        return experimentalType;
    }

    @Override
    public String displayText()
    {
        return text;
    }

    public static ShipModule findModule(String moduleName) throws Exception
    {
        final Exception exception;
        try
        {
            return valueOf(moduleName);
        }
        catch (Exception e)
        {
            exception = e;
            if (moduleName == null || moduleName.isEmpty()) throw e;
        }

        return Arrays.stream(CoreInternalModule.values())
                .filter(v->v.name().toLowerCase().equals(moduleName.toLowerCase()))
                .findFirst().orElseThrow(()->exception);
    }
}
