package com.controllerface.edeps.structures.equipment.ships;

import com.controllerface.edeps.data.BaseShipStats;
import com.controllerface.edeps.data.CoreModuleLayoutData;
import com.controllerface.edeps.data.HardPointLayoutData;
import com.controllerface.edeps.data.OptionalModuleLayoutData;
import com.controllerface.edeps.structures.equipment.modules.HardPointSize;
import com.controllerface.edeps.structures.equipment.modules.ModuleSize;

import java.util.Arrays;

/**
 * Created by Stephen on 4/16/2018.
 */
public enum Ship
{
    adder(
            BaseShipStats.builder()
                    .setDisplayName("Adder")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Zorgon_Peterson)
                    .setAgility(152)
                    .setHullMass(35)
                    .setHullHardness(35)
                    .setSpeed(220)
                    .setMaxSpeed(352)
                    .setBoostSpeed(320)
                    .setMaxBoostSpeed(512)
                    .setArmorRating(162)
                    .setBaseShield(60)
                    .setBaseCost(87_810)
                    .setMassLockFactor(7)
                    .setCrewSeats(2)
                    .setSlfCapable(false)
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_3)
                    .setThrusters(ModuleSize.SIZE_3)
                    .setFrameShiftDrive(ModuleSize.SIZE_3)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_2)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_3)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    cobramkiii(
            BaseShipStats.builder()
                    .setDisplayName("Cobra MKIII")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility(150)
                    .setHullMass(180)
                    .setHullHardness(35)
                    .setSpeed(280)
                    .setMaxSpeed(325)
                    .setBoostSpeed(400)
                    .setMaxBoostSpeed(464)
                    .setArmorRating(216)
                    .setBaseShield(80)
                    .setBaseCost(349_720)
                    .setMassLockFactor(8)
                    .setCrewSeats(2)
                    .setSlfCapable(false)
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_3)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .build()),

    cobramkiv(
            BaseShipStats.builder()
                    .setDisplayName("Cobra MKIV")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_3)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .build()),

    diamondbackxl(
            BaseShipStats.builder()
                    .setDisplayName("Diamondback Explorer")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_3)
                    .setPowerDistributor(ModuleSize.SIZE_4)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .build()),

    diamondback(
            BaseShipStats.builder()
                    .setDisplayName("Diamondback Scout")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_2)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_2)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    dolphin(
            BaseShipStats.builder()
                    .setDisplayName("Dolphin")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Saud_Kruger)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_5)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_4)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    eagle(
            BaseShipStats.builder()
                    .setDisplayName("Eagle")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_2)
                    .setThrusters(ModuleSize.SIZE_3)
                    .setFrameShiftDrive(ModuleSize.SIZE_3)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_2)
                    .setSensors(ModuleSize.SIZE_2)
                    .setFuelTank(ModuleSize.SIZE_2)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    hauler(
            BaseShipStats.builder()
                    .setDisplayName("Hauler")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Zorgon_Peterson)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_2)
                    .setThrusters(ModuleSize.SIZE_2)
                    .setFrameShiftDrive(ModuleSize.SIZE_2)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_1)
                    .setSensors(ModuleSize.SIZE_1)
                    .setFuelTank(ModuleSize.SIZE_2)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    empire_courier(
            BaseShipStats.builder()
                    .setDisplayName("Imperial Courier")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Gutamaya)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_3)
                    .setFrameShiftDrive(ModuleSize.SIZE_3)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_2)
                    .setFuelTank(ModuleSize.SIZE_3)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    empire_eagle(
            BaseShipStats.builder()
                    .setDisplayName("Imperial Eagle")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_3)
                    .setThrusters(ModuleSize.SIZE_3)
                    .setFrameShiftDrive(ModuleSize.SIZE_3)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_2)
                    .setSensors(ModuleSize.SIZE_2)
                    .setFuelTank(ModuleSize.SIZE_2)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    sidewinder(
            BaseShipStats.builder()
                    .setDisplayName("Sidewinder")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_2)
                    .setThrusters(ModuleSize.SIZE_2)
                    .setFrameShiftDrive(ModuleSize.SIZE_2)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_1)
                    .setSensors(ModuleSize.SIZE_1)
                    .setFuelTank(ModuleSize.SIZE_1)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .build()),

    viper(
            BaseShipStats.builder()
                    .setDisplayName("Viper MkIII")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_3)
                    .setThrusters(ModuleSize.SIZE_3)
                    .setFrameShiftDrive(ModuleSize.SIZE_3)
                    .setLifeSupport(ModuleSize.SIZE_2)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_2)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .build()),

    viper_mkiv(
            BaseShipStats.builder()
                    .setDisplayName("Viper MkIV")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_2)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .build()),

    vulture(
            BaseShipStats.builder()
                    .setDisplayName("Vulture")
                    .setShipSize(ShipSize.Small)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_5)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_3)
                    .setPowerDistributor(ModuleSize.SIZE_5)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_3)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    typex(
            BaseShipStats.builder()
                    .setDisplayName("Alliance Chieftain")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    asp(
            BaseShipStats.builder()
                    .setDisplayName("Asp Explorer")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_5)
                    .setThrusters(ModuleSize.SIZE_5)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_4)
                    .setPowerDistributor(ModuleSize.SIZE_4)
                    .setSensors(ModuleSize.SIZE_5)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    asp_scout(
            BaseShipStats.builder()
                    .setDisplayName("Asp Scout")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_3)
                    .setPowerDistributor(ModuleSize.SIZE_4)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    federation_dropship_mkii(
            BaseShipStats.builder()
                    .setDisplayName("Federal Assault Ship")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    federation_dropship(
            BaseShipStats.builder()
                    .setDisplayName("Federal Dropship")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    federation_gunship(
            BaseShipStats.builder()
                    .setDisplayName("Federal Gunship")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_7)
                    .setSensors(ModuleSize.SIZE_5)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    ferdelance(
            BaseShipStats.builder()
                    .setDisplayName("Fer-de-Lance")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Zorgon_Peterson)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_5)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_4)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_3)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Huge)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_1)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    independant_trader(
            BaseShipStats.builder()
                    .setDisplayName("Keelback")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_4)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_1)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_2)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    python(
            BaseShipStats.builder()
                    .setDisplayName("Python")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_7)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_4)
                    .setPowerDistributor(ModuleSize.SIZE_7)
                    .setSensors(ModuleSize.SIZE_6)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    type6(
            BaseShipStats.builder()
                    .setDisplayName("Type-6 Transporter")
                    .setShipSize(ShipSize.Medium)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_3)
                    .setThrusters(ModuleSize.SIZE_4)
                    .setFrameShiftDrive(ModuleSize.SIZE_4)
                    .setLifeSupport(ModuleSize.SIZE_2)
                    .setPowerDistributor(ModuleSize.SIZE_3)
                    .setSensors(ModuleSize.SIZE_2)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .build()),

    anaconda(
            BaseShipStats.builder()
                    .setDisplayName("Anaconda")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Faulcon_DeLacy)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_8)
                    .setThrusters(ModuleSize.SIZE_7)
                    .setFrameShiftDrive(ModuleSize.SIZE_6)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_8)
                    .setSensors(ModuleSize.SIZE_8)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Huge)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_7)
                    .build()),

    belugaliner(
            BaseShipStats.builder()
                    .setDisplayName("Beluga Liner")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Saud_Kruger)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_7)
                    .setFrameShiftDrive(ModuleSize.SIZE_7)
                    .setLifeSupport(ModuleSize.SIZE_8)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_5)
                    .setFuelTank(ModuleSize.SIZE_7)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    federation_corvette(
            BaseShipStats.builder()
                    .setDisplayName("Federal Corvette")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Core_Dynamics)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_8)
                    .setThrusters(ModuleSize.SIZE_7)
                    .setFrameShiftDrive(ModuleSize.SIZE_6)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_8)
                    .setSensors(ModuleSize.SIZE_8)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Huge)
                    .addHardPoint(HardPointSize.Huge)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_7)
                    .addModule(ModuleSize.SIZE_7)
                    .addModule(ModuleSize.SIZE_7)
                    .build()),

    empire_trader(
            BaseShipStats.builder()
                    .setDisplayName("Imperial Clipper")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Gutamaya)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_5)
                    .setFuelTank(ModuleSize.SIZE_4)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_7)
                    .build()),

    cutter(
            BaseShipStats.builder()
                    .setDisplayName("Imperial Cutter")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Gutamaya)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_8)
                    .setThrusters(ModuleSize.SIZE_8)
                    .setFrameShiftDrive(ModuleSize.SIZE_7)
                    .setLifeSupport(ModuleSize.SIZE_7)
                    .setPowerDistributor(ModuleSize.SIZE_7)
                    .setSensors(ModuleSize.SIZE_7)
                    .setFuelTank(ModuleSize.SIZE_6)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Huge)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_8)
                    .addModule(ModuleSize.SIZE_8)
                    .build()),

    orca(
            BaseShipStats.builder()
                    .setDisplayName("Orca")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Saud_Kruger)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_5)
                    .setThrusters(ModuleSize.SIZE_6)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_6)
                    .setPowerDistributor(ModuleSize.SIZE_5)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    type9_military(
            BaseShipStats.builder()
                    .setDisplayName("Type-10 Defender")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_8)
                    .setThrusters(ModuleSize.SIZE_7)
                    .setFrameShiftDrive(ModuleSize.SIZE_7)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_7)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_6)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .addHardPoint(HardPointSize.Large)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_7)
                    .addModule(ModuleSize.SIZE_8)
                    .build()),

    type7(
            BaseShipStats.builder()
                    .setDisplayName("Type-7 Transporter")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_5)
                    .setThrusters(ModuleSize.SIZE_5)
                    .setFrameShiftDrive(ModuleSize.SIZE_5)
                    .setLifeSupport(ModuleSize.SIZE_4)
                    .setPowerDistributor(ModuleSize.SIZE_4)
                    .setSensors(ModuleSize.SIZE_3)
                    .setFuelTank(ModuleSize.SIZE_5)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_6)
                    .build()),

    type9(
            BaseShipStats.builder()
                    .setDisplayName("Type-9 Heavy")
                    .setShipSize(ShipSize.Large)
                    .setManufacturer(ShipManufacturer.Lakon)
                    .setAgility()
                    .setHullMass()
                    .setHullHardness()
                    .setSpeed()
                    .setMaxSpeed()
                    .setBoostSpeed()
                    .setMaxBoostSpeed()
                    .setArmorRating()
                    .setBaseShield()
                    .setBaseCost()
                    .setMassLockFactor()
                    .setCrewSeats()
                    .setSlfCapable()
                    .build(),

            CoreModuleLayoutData.builder()
                    .setPowerPlant(ModuleSize.SIZE_6)
                    .setThrusters(ModuleSize.SIZE_7)
                    .setFrameShiftDrive(ModuleSize.SIZE_6)
                    .setLifeSupport(ModuleSize.SIZE_5)
                    .setPowerDistributor(ModuleSize.SIZE_6)
                    .setSensors(ModuleSize.SIZE_4)
                    .setFuelTank(ModuleSize.SIZE_6)
                    .build(),

            HardPointLayoutData.builder()
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Tiny)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Small)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .addHardPoint(HardPointSize.Medium)
                    .build(),

            OptionalModuleLayoutData.builder()
                    .addModule(ModuleSize.SIZE_2)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_3)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_4)
                    .addModule(ModuleSize.SIZE_5)
                    .addModule(ModuleSize.SIZE_6)
                    .addModule(ModuleSize.SIZE_7)
                    .addModule(ModuleSize.SIZE_8)
                    .addModule(ModuleSize.SIZE_8)
                    .build()),

    ;

    private final BaseShipStats baseShipStats;
    private final CoreModuleLayoutData coreModules;
    private final HardPointLayoutData hardpoints;
    private final OptionalModuleLayoutData internals;

    Ship(BaseShipStats baseShipStats, CoreModuleLayoutData coreModules, HardPointLayoutData hardpoints, OptionalModuleLayoutData internals)
    {
        this.baseShipStats = baseShipStats;
        this.coreModules = coreModules;
        this.hardpoints = hardpoints;
        this.internals = internals;
    }

    public static Ship findShip(String shipName) throws Exception
    {
        Exception exception;
        try
        {
            return valueOf(shipName);
        }
        catch (Exception e)
        {
            exception = e;
            if (shipName == null || shipName.isEmpty()) throw e;
        }
        return Arrays.stream(Ship.values())
                .filter(ship -> ship.name().toLowerCase().equals(shipName.toLowerCase()))
                .findFirst().orElseThrow(() -> exception);
    }
}
